name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install
        shell: bash
        run: pnpm install

      - name: 🔎 Typescript
        run: pnpm tsc --noEmit

      - name: 📦 Build
        run: pnpm build

      - name: Publish package on npm
        run: npx semantic-release@19 -b main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
