name: Release

on:
  release:
    types: [published]

concurrency:
  group: ci-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install
        shell: bash
        run: pnpm install

      - name: 🔎 Typescript
        run: pnpm tsc --noEmit

      - name: 📦 Build
        run: pnpm build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true
